### ISSUE TITLE
Unable to find the Toolbar Autohide App in the Firefox Add-Ons collection

### ISSUE THREAD

**Issue by simonkrausgit** [sparhami/fstbh#8]
I still have the extension on one of my laptops, but I'm unable to even find it anymore on my other machines online.

**Comment by sparhami** [comment]
I removed it from the add-on listing for a few of reasons. One reason is that there were a few bugs that were very difficult to work around on Windows. Another reason is that add-ons like Toolbar Autohide will no longer be supported in Firefox in the near future. Finally, there are other add-ons that provide a similar feature that could be used instead.

It would be nice if Firefox itself could incorporate some of the features of such toolbar hiding add-ons into the browser itself. Maintaining these sorts of features as an add-on is difficult since they very often conflict with other add-ons and have bugs introduced when Firefox makes internal changes.

**Comment by simonkrausgit** [comment]
Sad to hear about this regarding Firefox, but thanks for explaining!
